#!/bin/bash
GVT_PCI=0000:00:02.0                        
GVT_GUID=44975ace-fe4c-11ea-83b8-03805b0e769c
MDEV_TYPE=i915-GVTg_V5_4
DOMAIN=win10-virt        
if [ $# -ge 3 ]; then
    if [ $1 = "$DOMAIN" -a $2 = "prepare" -a $3 = "begin" ]; then
        echo "$GVT_GUID" > "/sys/bus/pci/devices/$GVT_PCI/mdev_supported_types/$MDEV_TYPE/create"
    elif [ $1 = "$DOMAIN" -a $2 = "release" -a $3 = "end" ]; then
        echo 1 > /sys/bus/pci/devices/$GVT_PCI/$GVT_GUID/remove
    fi
fi
